# Generated by Django 5.1 on 2026-03-31 19:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('avatar_uuid', models.CharField(blank=True, default='', max_length=36)),
                ('distance', models.FloatField(default=0.0)),
                ('is_sitting', models.BooleanField(default=False)),
                ('scripted_attachments_count', models.PositiveIntegerField(default=0)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'avatars',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('region_uuid', models.CharField(blank=True, default='', max_length=36)),
                ('map_image_url', models.URLField(blank=True, default='')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_scanned', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='scanning.avatar')),
            ],
            options={
                'db_table': 'attachments',
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('owner_name', models.CharField(blank=True, default='', max_length=100)),
                ('coordinates', models.CharField(blank=True, default='', max_length=100)),
                ('scanned_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='scanning.region')),
            ],
            options={
                'db_table': 'parcels',
            },
        ),
        migrations.AddField(
            model_name='avatar',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to='scanning.region'),
        ),
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_key', models.CharField(blank=True, default='', max_length=36)),
                ('avatar_count', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_sessions', to='scanning.region')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scan_sessions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='avatar',
            name='scan_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to='scanning.scansession'),
        ),
    ]
