# Generated by Django 5.1 on 2026-03-31 19:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordWebhookConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('webhook_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('notify_new_avatar', models.BooleanField(default=True)),
                ('notify_specific_avatars', models.TextField(blank=True, default='', help_text='Comma-separated names')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discord_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discord_webhook_configs',
            },
        ),
    ]
